#!/usr/bin/python3
#
# CherryMusic - a standalone music server
# Copyright (c) 2012 Tom Wallroth & Tilman Boerner
#
# Project page:
#   http://fomori.org/cherrymusic/
# Sources on github:
#   http://github.com/devsnd/cherrymusic/
#
# CherryMusic is based on
#   jPlayer (GPL/MIT license) http://www.jplayer.org/
#   CherryPy (BSD license) http://www.cherrypy.org/
#
# licensed under GNU GPL version 3 (or later)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

import cherrymusicserver
try:
	import argparse
except ImportError:
	#python 3.1 workaround, can be dropped once 3.2 is in debian.
	import optparse as argparse
	argparse.ArgumentParser = argparse.OptionParser
	argparse.ArgumentParser.add_argument = argparse.ArgumentParser.add_option
	argparse.ArgumentParser.__parse_args__ = argparse.ArgumentParser.parse_args
	def parseargs(self):
		return self.__parse_args__()[0]
	argparse.ArgumentParser.parse_args = parseargs
    #end of workaround

parser = argparse.ArgumentParser(description='''CherryMusic Server
Version '''+cherrymusicserver.VERSION)

parser.add_argument('--update',dest='update',action='store_true', help='update the media database')
parser.add_argument('--newconfig',dest='newconfig',action='store_true', help='creates a new config file in your home directory, e.g. ~/.cherrymusic/config.new')
args = parser.parse_args()

if __name__ == "__main__":
    cherrymusicserver.CherryMusic(update=args.update,createNewConfig=args.newconfig)
    
