web:
  extends:
    file: config.yml
    service: web
  expose:
    - "8000"
  volumes:
    - /tmp
    - ./web:/usr/src/app
  command: /usr/local/bin/gunicorn cherrymusic.wsgi:application -w 6 -b :8000 --timeout 5000

nginx:
  build: ./nginx/
  ports:
    - "80:80"

postgres:
  image: postgres:latest
  expose:
    - "5432"

redis:
  image: redis:latest
  expose:
    - "6379"

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
