web:
  extends:
    file: config.yml
    service: web
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /tmp
    - ./web:/usr/src/app
  env_file: .env
  command: /usr/local/bin/gunicorn cherrymusic.wsgi:application -w 6 -b :8000 --timeout 5000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
    - postgres:postgres
    - redis:redis

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  expose:
    - "5432"

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
