#!/bin/sh
#
# CherryMusic - a standalone music server
# Copyright (c) 2012 Tom Wallroth & Tilman Boerner
#
# Project page:
#   http://fomori.org/cherrymusic/
# Sources on github:
#   http://github.com/devsnd/cherrymusic/
#
# CherryMusic is based on
#   jPlayer (GPL/MIT license) http://www.jplayer.org/
#   CherryPy (BSD license) http://www.cherrypy.org/
#
# licensed under GNU GPL version 3 (or later)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
##############################################################################
#
# run a number of tests for the project
#
##############################################################################

PROJECTDIR=`dirname $0`

if [ ! -d ${PROJECTDIR} -o ! -f ${PROJECTDIR}/cherrymusic ]; then
    echo "cannot find main script: 'cherrymusic'" >&2
    echo "PROJECTDIR not set correctly? to fix, edit $0" >&2
    exit 1
fi

echo "checking dist metadata..."
python ${PROJECTDIR}/setup.py check
if [ $? != 0 ]; then
    echo "distribution metadata check failure" >&2
    exit 1
fi
echo "done."


# nosetests
for i in "" "2" "3"; do
    cmd="nosetests${i}"
    if [ $(command -v $cmd) ]; then
        echo "running ${cmd}:"
        $cmd -e cherrypy
        if [ $? != 0 ]; then
            failed="$failed $cmd"
        else
            passed="$passed $cmd"
        fi
    fi
done

if [ "$failed" ]; then
    echo "FAILED: $failed" >&2
    exit 1
fi

if [ ! "$passed" ]; then
    echo "no unittest runners found!" >&2
    echo "get nosetests from https://nose.readthedocs.org/en/latest/" >&2
    exit 1
fi
