#!/bin/sh
#
# CherryMusic - a standalone music server
# Copyright (c) 2012 Tom Wallroth & Tilman Boerner
#
# Project page:
#   http://fomori.org/cherrymusic/
# Sources on github:
#   http://github.com/devsnd/cherrymusic/
#
# CherryMusic is based on
#   jPlayer (GPL/MIT license) http://www.jplayer.org/
#   CherryPy (BSD license) http://www.cherrypy.org/
#
# licensed under GNU GPL version 3 (or later)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
##############################################################################
#
# run a number of tests for the project
#
##############################################################################

PROJECTDIR=`dirname $0`
SPECIFIC_TEST="$1"

TEST_EXCLUDE_REGEX='cherrypy'
TEST_OPTIONS="--with-coverage --cover-erase"

if [ ! -d ${PROJECTDIR} -o ! -f ${PROJECTDIR}/cherrymusic ]; then
    echo "cannot find main script: 'cherrymusic'" >&2
    echo "PROJECTDIR not set correctly? to fix, edit $0" >&2
    exit 1
fi

if [ $SPECIFIC_TEST ]; then
    TEST_LOCATION="cherrymusicserver.test.test_${SPECIFIC_TEST}"
    COVERAGE_TARGET="cherrymusicserver.${SPECIFIC_TEST}"
    TEST_OPTIONS="${TEST_OPTIONS} --cover-package=${COVERAGE_TARGET} --cover-branches --cover-min-percentage=100"
    TEST_OPTIONS="${TEST_OPTIONS} --no-deprecated"
else
    TEST_LOCATION=""
    COVERAGE_TARGET="audiotranscode,cherrymusicserver,cmbootstrap"
    TEST_OPTIONS="${TEST_OPTIONS} --cover-package=${COVERAGE_TARGET} --cover-min-percentage=50"
    TEST_OPTIONS="${TEST_OPTIONS} --no-skip"

    echo
    echo "[distribution]: setup.py check"
    python ${PROJECTDIR}/setup.py check
    if [ $? != 0 ]; then
        echo "distribution metadata check failure" >&2
        exit 1
    fi
    echo "done."
fi


# nosetests
for i in "" "2" "3"; do
    TESTER="nosetests${i}"
    if [ $(command -v $TESTER) ]; then
        RUN="${TESTER} -e ${TEST_EXCLUDE_REGEX} ${TEST_OPTIONS} ${TEST_LOCATION}"
        echo
        echo "[${TESTER}]: ${RUN}"
        $RUN
        if [ $? != 0 ]; then
            failed="$failed $TESTER"
        else
            passed="$passed $TESTER"
        fi
    fi
done

# doctests
if [ $SPECIFIC_TEST ]; then
    TESTER="python -m doctest"
    TEST_OPTIONS=""
    TEST_LOCATION="cherrymusicserver/${SPECIFIC_TEST}.py"
    if [ $(command -v $TESTER) ]; then
        RUN="${TESTER} ${TEST_OPTIONS} ${TEST_LOCATION}"
        echo
        echo "[${TESTER}]: ${RUN}"
        $RUN
        if [ $? != 0 ]; then
            failed="$failed doctest"
        else
            echo "OK"
        fi
    fi
fi

if [ "$failed" ]; then
    echo "FAILED: $failed" >&2
    exit 1
fi

if [ ! "$passed" ]; then
    echo "no unittest runners found!" >&2
    echo "get nosetests from https://nose.readthedocs.org/en/latest/" >&2
    exit 1
fi
