.\" Manpage for CherryMusic.
.\" Contact us on github.com/devsnd/cherrymusic to correct errors or typos.

.TH "CHERRYMUSICD" "8" "2013\-05\-16" "CherryMusic" "cherrymusicd man page"

.SH "NAME"
cherrymusicd \- the daemon for CherryMusic, see \fBcherrymusic\fP(1)

.SH "SYNOPSIS"
cherrymusicd [OPTIONS]

.SH "DESCRIPTION"
CherryMusic can also be started as a daemon.

.SH "OPTIONS"
.\.IP "\fB-option\fP"
Right now, cherrymusicd does not take any options.

.SH "FILES"
According to XDG Base Directory Specification, CherryMusic honors $XDG_DATA_HOME and $XDG_CONFIG_HOME. If these variables are empty or not set, files are stored using the standard path:

~/.config/cherrymusic/cherrymusic.conf
.PP
~/.local/share/cherrymusic

.SH "SEE ALSO"
.PP
\fBcherrymusic\fP(1), \fBcherrymusic.conf\fP(5)

.SH "BUGS"
You've found a bug in CherryMusic? That's awesome. Tell us about it! You can open an issue in the issue tracker of our github project page (github.com/devsnd/cherrymusic/issues) and we'll take care of it.

.SH "AUTHORS"
CherryMusic was created by Tom Wallroth and is currently developed together with Tilman Börner.

.SH "COPYRIGHT"
GNU GENERAL PUBLIC LICENSE - Version 3, 29 June 2007
