# Generated by Django 2.1.4 on 2018-12-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('meta_index_date', models.DateField(blank=True, null=True)),
                ('meta_track', models.IntegerField(blank=True, null=True)),
                ('meta_track_total', models.IntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_album', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_year', models.IntegerField(blank=True, null=True)),
                ('meta_genre', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_duration', models.FloatField(blank=True, null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.Directory')),
            ],
        ),
    ]
